# workers/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  namespace: hackathon
spec:
  selector:
    matchLabels:
      app: workers
  replicas: 2  # Run multiple workers for parallelism
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: worker
        image: busybox:1.36
        command: ["sh", "-c", "echo 'Worker ready to process messages'; sleep 3600"]
        env:
        - name: RABBITMQ_URL
          value: "amqp://message-queue:5672"
        - name: DATABASE_URL
          value: "postgresql://hackathon:hackathon@database:5432/hackathon"