# web-app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: hackathon
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:1.23
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://hackathon:hackathon@database:5432/hackathon"
        - name: RABBITMQ_URL
          value: "amqp://message-queue:5672"