# message-queue/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-queue
  namespace: hackathon
spec:
  selector:
    matchLabels:
      app: message-queue
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11-management
        ports:
        - containerPort: 5672  # AMQP port
        - containerPort: 15672 # Management UI