# database/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: hackathon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi