# database/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: hackathon
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP